baseURL: "https://upendra1997.github.io/"
title: Blog | Upendra Upadhyay
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: "G-10K1DEGGW1"

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Upendra - Blog
    description: "Personal Blog"
    keywords: [Blog, Portfolio, PaperMod]
    author: Upendra Upadhyay
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false
    ShowFullTextinRSS: true

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Home"
        # icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Upendra Upadhyay
        subtitle: |
          I am Software Engineer who likes problem solving, programming languages, databases, AI and learning new things in general. I like to dabble in solving problems in Haskell, Rust and read books like SICP, DDIA, clean code, etc. 
          Few of my guilty pleasures are reading books(Academic/LightNovels/Wuxia/Manga), watching Anime, TV-Shows, and just browsing YouTube.
        imageUrl: "https://s.gravatar.com/avatar/242925530ed1bc0f579be4ae131abc1d?s=1000"
        imageWidth: 120
        imageHeight: 120
        imageTitle: Upendra Upadhyay
        buttons:
            # - name: Posts
            #   url: posts
            # - name: Tags
            #   url: tags
            # - name: Archives
            #   url: archives
            - name: Resume
              url: resume

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/upendra-upadhyay/"
        - name: facebook
          url: "https://www.facebook.com/upendra.upadhyay.97"
        - name: twitter
          url: "https://twitter.com/hdggxin"
        - name: github
          url: "https://github.com/upendra1997"
        - name: codepen
          url: "https://codepen.io/hdggxin/"
        - name: youtube
          url: "https://www.youtube.com/channel/UCGbSuHBYqbBAlK3gxU2AT0g"
        - name: "instagram"
          url: "https://www.instagram.com/upendra.upadhyay.97/"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/8502345/upendra-upadhyay"
        - name: rss
          url: "https://upendra1997.github.io/index.xml"

    analytics:
        google:
            SiteVerificationTag: "G-10K1DEGGW1"
        # bing:
        #     SiteVerificationTag: "XYZabc"
        # yandex:
        #     SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page
        linkFullImages: true

    editPost:
        URL: "https://github.com/upendra1997.github.io/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: posts
          name: posts
          url: /posts/
          weight: 1
        - identifier: Archive
          name: archives
          url: archives
          weight: 2
        - identifier: Search
          name: search
          url: search/
          weight: 3
        - identifier: tags
          name: tags
          url: /tags/
          weight: 4
        - identifier: categories
          name: categories
          url: /categories/
          weight: 5
        - identifier: resume
          name: resume
          url: /resume/
          weight: 6
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
disqusShortname: "upendra1997-github-io"
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
